// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const CreditCardsSecretsSchema = z.object({
  id: z.string().uuid(),
  consumerSecretsId: z.string().uuid(),
  cardName: z.string(),
  cardHolderName: z.string(),
  encryptedCardNumber: zodBuffer,
  encryptedCvv: zodBuffer,
  encryptedExpirationDate: zodBuffer,
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TCreditCardsSecrets = z.infer<typeof CreditCardsSecretsSchema>;
export type TCreditCardsSecretsInsert = Omit<z.input<typeof CreditCardsSecretsSchema>, TImmutableDBKeys>;
export type TCreditCardsSecretsUpdate = Partial<Omit<z.input<typeof CreditCardsSecretsSchema>, TImmutableDBKeys>>;
