// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { zodBuffer } from "@app/lib/zod";

import { TImmutableDBKeys } from "./models";

export const SecureNotesSecretsSchema = z.object({
  id: z.string().uuid(),
  customerSecretsId: z.string().uuid(),
  title: z.string(),
  encryptedNote: zodBuffer,
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecureNotesSecrets = z.infer<typeof SecureNotesSecretsSchema>;
export type TSecureNotesSecretsInsert = Omit<z.input<typeof SecureNotesSecretsSchema>, TImmutableDBKeys>;
export type TSecureNotesSecretsUpdate = Partial<Omit<z.input<typeof SecureNotesSecretsSchema>, TImmutableDBKeys>>;
